name: Integração Contínua

on:
  workflow_call:
    
jobs:
  docker :
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-20.04', 'ubuntu-22.04']
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.7.1
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ferrarix
        password: Dasv+6262
